export const Backgrounds = [
    {
      Name: "Aurifex",
      Description:
        "You are an artisan of the arcane, a smith of subtle forces. In the crucible of your workshop, the laws that govern this world are warped to suit your needs.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Needle-Knife",
          Damage: "d6",
        },
      ],
      Gear: ["Rations (3 uses)", "Lantern", "Oil Can (6 uses)"],
      PettyGear: ["Protective Gloves"],
      Names: [
        "Hestia",
        "Basil",
        "Rune",
        "Prism",
        "Ember",
        "Quintess",
        "Aludel",
        "Mordant",
        "Salaman",
        "Jazia",
      ],
      HistoryLabel: "What experiment went horribly wrong?",
      Histories: [
        "There was an explosion, and you lost your sense of smell. Well, almost: you can sniff out gold as a pig does truffles. Take a Tin of Snuff (6 uses) to dampen the impact. Use it every day or become deprived.",
        "You dematerialized a beloved pet. Now it follows you around, invisible but always present. Although it cannot interact with the physical realm, you are able to share its sense. (Add a Fatigue each time.) It follows basic commands.",
        "You were exposed to a long-acting truth serum whose effects have yet to wear off. The disorder has its advantages: you cannot repeat lies you’ve heard, either.",
        "You were adept at creating fake gold, which is almost as good. Eventually, your ruse was discovered, and you had to make a hasty retreat. Take a heavy Metal Ingot and Gold Powder (3 uses).",
        "Your alchemical recipe worked, but a rival stole the blueprint before your claims could be proven. Take a prototype Blunderbuss (d12, blast, bulky) that takes one round to reload, and a taste for revenge.",
        "Ridiculed for discovering how to turn gold into lead, you were a laughing stock. Take a bottle of Universal Solvent (2 uses) that dissolves anything it touches into its constituent parts.",
      ],
      SpecialLabel:
        "What alchemical marvel is the product of your latest ingenuity?",
      Specials: [
        "Pyrophoric Gel: A sticky green fluid that catches fire when exposed to air, then burns for 8 hours. Cannot be extinguished (1 use).",
        "Blast Sphere: A head-sized iron ball filled with explosive powder that explodes on impact (d12, blast, bulky, 1 use).",
        "Aqua Vita: Purifies any liquid, converting it to pure water. Drinking it cures 1d6 STR (1 use).",
        "Mimic Stone: Records a short phrase that can later be played back.",
        "Spark Dust: Ignites easily and quickly. Useful for starting a fire or as an incendiary device (3 uses).",
        "Homunculus: A miniature clay replica of yourself that follows your every command. It hates being enthralled to you and complains bitterly whenever possible. Any damage done to the homunculus is also done to you. 3 HP, 4 STR, 13 DEX, 5 WIL",
      ],
    },
    {
      Name: "Barber-Surgeon",
      Description:
        "You walk the line between healer and harrower, knowing the frailty of the flesh but also the secrets that lie within. With the right tools, life and death are merely words.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Amputation Knife",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Bandages (3 uses)",
        "Leech (restores 1 STR, 3 uses)",
      ],
      PettyGear: ["Stained Medical Finery"],
      Names: [
        "Wilmot",
        "Patch",
        "Lancet",
        "Sawbones",
        "Theo",
        "Cutwell",
        "Humor",
        "Landsford",
        "Goodeye",
        "Johanna",
      ],
      HistoryLabel: "How have you “improved” yourself?",
      Histories: [
        "You have a replacement eye that can magnify objects, act as a telescope, and provide minimal night vision. You cannot wear anything metal on your head, and strong magnets make you deprived.",
        "One foot is mostly metal (kick, d6), and you treat some Tough Terrain as Easy. Carry an Oil Can (6 uses). Without a daily application, you are deprived and noisy.",
        "One of your fingers has been swapped, the bone replaced by gold and iron. Take a Hook and a Screwdriver that can attach to the fingertip.",
        "Both ears have been surgically enhanced, tripling your hearing. You can focus on a specific sound, such as a conversation, at a great distance. You wear an ear flap to protect against sudden loud noises (WIL save to avoid temporary paralysis).",
        "Your chest is lined with alchemical sigils, toughening the skin (1 Armor). Wearing other metallic armor nullifies the effect.",
        "One arm is fully metal and comes off at the shoulder. It can be used as a weapon (d8, bulky when not attached) and can move independently if you are within sight of it.",
      ],
      SpecialLabel: "What rare tool is essential to your work?",
      Specials: [
        "Regrowth Salve: Regrows a body part over the course of a day (1 use).",
        "Graftgrub: A small worm that can fuse inanimate objects with parts of the body (1 use).",
        "Woundwax: Heals wounds from fire or chemicals (restoring full STR) but nothing else (2 uses).",
        "Quicksilver: A stimulant. Go first in combat, and automatically pass any WIL saves for one hour. Addictive: Save STR or become deprived after 24 hours without it (4 uses).",
        "Pneuma Pump: Portable iron lungs (bulky). Enables life-saving surgery or underwater breathing.",
        "Lodestone: Draws out dangerous elements from the body, and acts as a powerful magnetic force.",
      ],
    },
    {
      Name: "Beast Handler",
      Description:
        "You alone can walk among the creatures of the wild, fearless and in control. You share a connection with animals that others can only dream of...so long as you don’t become their snack.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Leather Whip",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Soporific Darts (STR save or fall asleep, 6 uses)",
        "Lure",
        "Rope (25ft)",
      ],
      PettyGear: [],
      Names: [
        "Amara",
        "Wulf",
        "Mireille",
        "Soren",
        "Freki",
        "Aster",
        "Gerrik",
        "Boreas",
        "Veda",
        "Matheus",
      ],
      HistoryLabel: "What creature is your specialty?",
      Histories: [
        "Arachnid: Take a Quick-Flame Rod and an Oil Can (6 uses). It can destroy a large spider nest in seconds.",
        "Feline: Take a sack of Whiskerwort. Its odor can calm and control even the largest of cats.",
        "Canine: Take a wreath of Wolfsbane and a Large Net. Also effective against werewolves!",
        "Bird: Take a Warble-Whistle (3 charges). It can imitate any bird call and can even be used to send simple messages. Recharge: Feed a baby bird as its mother would, then blow.",
        "Rodent: Take a Windpipe that emits a high-pitched sound that only rodents can hear. So long as you play, they will follow, even to their deaths.",
        "Serpent: Take a Warming Stone that generates an irresistible heat and a vial of Antitoxin (2 uses).",
      ],
      SpecialLabel:
        "What do creatures of the wild understand that your kind do not?",
      Specials: [
        "There is far more to the world than meets the eye. With quiet concentration, you can borrow the senses of a nearby creature of your specialty.",
        "The behavior of beasts is a language in itself. When observing beasts of your specialty, you gain insight into weather patterns and impending disasters.",
        "The pulse of the hunt is a powerful impulse. You have a sense for when predators, even those not of your specialty, are near.",
        "You know some lands intimately. Your chance of becoming lost in a terrain dominated by the beasts of your specialty is reduced by one step (e.g. 4-in-6 becomes 3-in-6).",
        "Nature’s symphony can be heard if you attune to its rhythm. When surrounded by creatures of your specialty, they can alert you to approaching danger before it arrives.",
        "Survival is about adaptability. Once per day, you may take on a simple feature from a creature of your specialty (webbed fingers, night vision, etc.). Add a Fatigue each time.",
      ],
    },
    {
      Name: "Bonekeeper",
      Description:
        "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Stake",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Lantern",
        "Oil Can (6 uses)",
        "Chains (10ft)",
      ],
      PettyGear: [],
      Names: [
        "Rook",
        "Ebon",
        "Moro",
        "Yew",
        "Pall",
        "Leth",
        "Lenore",
        "Barnaby",
        "Vesper",
        "Leder",
      ],
      HistoryLabel: "What did you take from the dead?",
      Histories: [
        "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
        "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
        "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
        "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
        "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
        "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
      ],
      SpecialLabel: "What tool was invaluable in your work?",
      Specials: [
        "Manacles: Though old, it’s still effective even against the very strong. You don’t have the key.",
        "Sponge: Supposedly made from the remains of a rare sea creature. It never seems to dry out.",
        "Pulley: Great for moving gravestones, rocks, or even bodies.",
        "Incense: Perfect for rituals or to keep the flies at bay. Cools the blood.",
        "Crowbar: d6 damage. Sometimes you just need to get the damn thing open!",
        "Repellent: Powerful stuff. Its faded label makes it unclear what it is actually meant to repel, though. Perhaps everything. 3 uses.",
      ],
    },
    {
      Name: "Cutpurse",
      Description:
        "You live in the grey space between those who have power and those who don’t. You find opportunity where others see only chaos. With nimble fingers, you unburden both the richest merchant and the lowliest guard.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Twin Daggers, bulky",
          Damage: "d6+d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Padded Leather (1 Armor)",
        "Lockpicks",
        "Black Outfit (petty)",
      ],
      PettyGear: [],
      Names: [
        "Arlo",
        "Lyra",
        "Eamon",
        "Salina",
        "Elara",
        "Freya",
        "Bull",
        "Sparrow",
        "Ivy",
        "Silas",
      ],
      HistoryLabel: "What was you last big job?",
      Histories: [
        "A noble’s summer home. The place was full of fancy wine (+20gp) but not much else. Take Fence Cutters.",
        "A bank. (You were caught.) You bear a brand only visible by firelight, and anyone who sees the mark can ask you for a beer. Take Retractable Wires.",
        "A guild warehouse. Take a Ladder (bulky, 10ft) and Blinding Powder (1 use).",
        "Moneylender. Someone beat you to the job but left behind a Scroll of Arcane Eye (petty). Arcane Eye: You can see through a magical floating eyeball that flies around at your command.",
        "Constable’s quarters. You escaped but left some friends behind. Take Strong Silk Rope and a queasy feeling.",
        "A university. You were seen but not pursued. You still don’t know why. Take Smoke Pellets (3 uses).",
      ],
      SpecialLabel: "What helps you steal?",
      Specials: [
        "Catring: 2 charges. Climb up walls and fall safely. Recharge: Place the ring on a stray cat's tail.",
        "Gildfinger: 1 charge. A finger glove that mimics any mundane key. Recharge: Bundle it with at least 100gp for a night.",
        "Glimpse Glass: 3 uses. A monocle that lets you see through walls or other obstructions. It shatters after the last use.",
        "Sweetwhistle: 1 charge. Listeners hear a soft, familiar voice in the distance that they cannot resist following. Recharge: Lose a dear memory. (Describe it.)",
        "Vagrant's Veil: 1 charge. Wear it to blend seamlessly into crowds, appearing as a simple pauper. Recharge: Donate all the day’s winnings to the poor. Petty.",
        "Reverse Teetotum: 1 use. When spun, time skips backwards 30 seconds. Everyone remembers what happened.",
      ],
    },
    {
      Name: "Fieldwarden",
      Description:
        "Protectors of the harvest, defense against pests, thieves, and beasts. A position of great honor, while it lasts: many guardians do not live out their natural lives. Roll a second time on the Bonds table.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Sling",
          Damage: "d6",
        },
        {
          Name: "Hand Axe",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Brigandine (1 Armor, bulky)",
        "Repellent (pick the type, 3 uses)",
      ],
      PettyGear: [],
      Names: [
        "Seed",
        "Thresh",
        "Dibber",
        "Sow",
        "Stalk",
        "Harrow",
        "Cobb",
        "Flax",
        "Briar",
        "Rye",
      ],
      HistoryLabel: "What got the better of you?",
      Histories: [
        "A voracious swarm of pests that swallowed crops and animals alike. With nothing to defend, you left. Take Gale Seed Extract (3 uses). Ingesting it lets you sprint with a speed four times your regular rate. Afterward you add two Fatigue.",
        "A crop spirit, angered by a poor tithing. The fires consumed nearly everything, and afterward you were able to gather a pouch of Fireseeds (d8, blast, 4 uses).",
        "An antlered, toothy demon that nearly ended you. Take a blood-stained bone knife (d6). On Critical Damage, its next attack becomes enhanced from contact with blood.",
        "The Withering, a type of stem rot from the Roots. Take a Diseased Crop (6 uses) that decays any plant it touches.",
        "Wolves, or so you thought. You are now a Werewolf [8 HP, 15 STR, 14 DEX, claws (d6+d6), bite (d8)]. Your WIL remains the same. You can turn at will (once per day) but must make a WIL save to revert. Anyone left alive from your attacks must make a WIL save to avoid infection.",
        "Crop thieves. Not all of them survived, but you were outnumbered. Start with +d4 HP and a Cusped Falchion (d8).",
      ],
      SpecialLabel: "What tool saved your life?",
      Specials: [
        "Bloodvine Whip: d8 damage. On Critical Damage, it drains the target’s blood, granting the weapon’s next attack the blast quality.",
        "Clatter Keeper: A hand-cranked device that emits a loud noise, frightening away most creatures.",
        "Sun Stick: Provides ample warmth and light for up to one hour (1 use). Recharge: Leave in heavy sunlight for a full day.",
        "Root Tether: When thrown, binds a creature as large as a wolf to the soil for a short time.",
        "Greenwhistle: A small flute that calms plants, making passage through areas heavy with plant life a bit easier.",
        "Everbloom Band: A circlet adorned with flowers that never wilt. On Critical Damage, the flowers dissolve into dust, but you act as if your save succeeded (STR loss still occurs).",
      ],
    },
    {
      Name: "Fletchwind",
      Description:
        "You strike from afar, but that does not make you a coward. You are a musician, the song of your bowstring nought but a warning, singing the silent promise of a quick death.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Serrated Knife",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Bow (see table)",
        "Boiled Leather (1 Armor)",
        "Heartroot Salve (restores 1d4 STR, 1 use)",
      ],
      PettyGear: [],
      Names: [
        "Flint",
        "Feather",
        "Crier",
        "Thunder",
        "Falcon",
        "Pluck",
        "Needle",
        "Warsong",
        "Hawk",
        "Cai",
      ],
      HistoryLabel: "How did you earn your bow?",
      Histories: [
        "War. If you are first to attack, your bow gains the blast property for the first round.",
        "Falconry. You keep a falcon [3 hp, 5 STR, 16 DEX, 4 WIL, claws (d6+d6), bite (d8)]. It only eats live game.",
        "Hunting. When taking the Supply (pg. 79) action, your ability to secure Rations increases by one step (e.g. 1d4 becomes 1d6).",
        "Tournaments. Attacks with your bow are enhanced if the target is immobile.",
        "Training. If you are the first to attack, melee attacks against you are impaired until you take STR damage.",
        "Scouting. When taking the Travel (pg. 79) action, your presence decreases the chance of getting lost by one step (e.g. 4-in-6 becomes 3-in-6).",
      ],
      SpecialLabel: "What kind of wood is your bow made from?",
      Specials: [
        "Western Yew (d6, bulky). Can be wielded as a blunt weapon (d6). Noisy.",
        "Sessile Oak (d8, bulky). Slams into targets. On Critical Damage, something is torn off.",
        "Stone Pine (d6, bulky). Produces one use of Sticky Sap per day. The sap is highly explosive.",
        "White Ash (d6, bulky). Can be used in place of a shield in melee combat (+1 Armor).",
        "Striped Bamboo (d6). Collapsible, it only requires one slot (but still requires both hands).",
        "Wych Elm (d6, bulky). Protects the bearer from poisons and toxins, so long as they are holding it.",
      ],
    },
    {
      Name: "Foundling",
      Description:
        "An odd birthmark, a strange smell: somehow, the touch of elsewhere still lingers. Wherever you are, you have trouble fitting in. Roll on the Omens table (even if you’re not the youngest player), but keep the results private for now.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Sling",
          Damage: "d6",
        },
        {
          Name: "Dagger",
          Damage: "d6",
        },
      ],
      Gear: ["Rations (3 uses)", "Torch (3 uses)", "Salt Pouch"],
      PettyGear: ["Heirloom Amulet (petty, glows in the presence of magic)"],
      Names: [
        "Faunus",
        "Snowdrop",
        "Wisp",
        "Silverdew",
        "Brim",
        "Solstice",
        "Steeleye",
        "Artea",
        "Gossamer",
        "Hazel",
      ],
      HistoryLabel: "Who took you in?",
      Histories: [
        "An old hunter. You were both quite happy, until it all ended. Take a Weathered Longbow (d8, bulky) and a Leather Jerkin (1 Armor).",
        "A wizened apothecary, who taught you the healing arts but maintained a clinical detachment. Take a Healing Unguent (restores d4 STR, 1 use).",
        "A druid, who taught you the language of trees. When it came time to leave, 3 you took with you only a Gnarled Staff (d8) and left a promise that one day you would return.",
        "A gruff blacksmith from a sleepy river town. You were always kept at arm’s length. Now the forge is cold, and you’ve moved on. Take a Smith’s Apron (petty) and a set of oft-mended Chain Mail (2 Armor, bulky).",
        "A troupe of traveling entertainers. For a time, they were like family to you. One day you woke up and they were gone with no explanation. Take a Storybook, a Dagger (d6), and some burning questions.",
        "The monks of a secluded forest monastery. When their rules became too strict, you snuck away. Take a Monk’s Habit (warm, petty) and a Spellbook of Control Plants. Control Plants: Nearby plants and trees obey you and gain the ability to move at a slow pace. Leaves grow along the spine, and it smells faintly of decay.",
      ],
      SpecialLabel: "What keeps away bad tidings?",
      Specials: [
        "Pipeweed: Your good luck charm. Conversations tend to flow more easily after a smoke (6 uses).",
        "Stink Jar: Shattering this jar releases an odor so foul all nearby must make a STR save or immediately vomit (1 use).",
        "Ivy Worm: A green worm often mistaken for a weed. Swallowed whole, it absorbs any toxins or rot in the body before exiting through the usual way.",
        "Dream Stone: A smooth blue stone that helps recall dreams more clearly. Overuse can cause dream-addiction.",
        "Drowning Rod: A finger-sized wooden stick that doubles in size each time it is fully submerged in water. It doesn’t shrink back down.",
        "Rabbit's Foot: You were wearing it when they found you. They say it is the foot of she who left you and that it protects you from witch magic (petty).",
      ],
    },
    {
      Name: "Fungal Forager",
      Description:
        "You follow the whisperings of the deep earth, the rhythmic pulse of the mycelium forest that grows beneath the surface. The dark holds no terror for you. Also, you really love mushrooms.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Sharpened Trowel",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Candle Helmet (+1 Armor, dim, 6 uses)",
        "Rope (25ft)",
        "Metal Pail",
      ],
      PettyGear: [],
      Names: [
        "Unther",
        "Woozy",
        "Hilda",
        "Current",
        "Leif",
        "Ratan",
        "Mourella",
        "Lal",
        "Per",
        "Madrigal",
      ],
      HistoryLabel: "What strange fungus did you discover?",
      Histories: [
        "Shrieking Trumpet. When exposed to light, it screams so loudly that all nearby attacks (including your own) are impaired (2 uses).",
        "Torch Fungus. When crushed, it creates a cold blue light for a short while. (2 uses).",
        "Murderous Truffle. Pungent, highly toxic, and very rare (worth 50gp to assassins). Illegal pretty much everywhere (1 use).",
        "Hellcap. Exposure to its aroma causes intense nausea, even vomiting. Either way, it clears the room. Bottled (1 use).",
        "Sproutcup. Ingest to shrink down to the size of a mouse. (Your belongings stay the same size.) You return to normal size within the hour, often in fits and starts (1 use).",
        "Rootflower. A white fungus found only on corpses deep underground. Ingest to restore d6 WIL. You will dream of the dead and their stories (1 use).",
      ],
      SpecialLabel: "What keeps you sane, even in utter darkness?",
      Specials: [
        "Glowsnail - Casts a soft, bioluminescent light. Feeds on one ration every two days.",
        "Silk Moth Shawl - A weatherproof blanket, it can also douse a fire without being damaged.",
        "Milkflower - A gentle stimulant. Chewing it makes you immune to panic for the next hour (3 uses).",
        "Luxcompass - Hums softly as it moves closer to the Sun. Eventually the noise becomes unbearably loud.",
        "Sloth-Tarp - A tough and weatherproof fabric, useful for hanging off trees. When inside, you have +1 Armor.",
        "Miner's Grease - Great for dislodging a gem, tool, or limb from a tight crack. Highly explosive (3 uses).",
      ],
    },
    {
      Name: "Greenwise",
      Description:
        "You delve deep into the Wood, prying its secrets from between rough boughs and whispering leaves. To this verdant kingdom, you are no mere scholar but its confidant as well.",
      GoldDice: [3, 6],
      Weapons: [
        {
          Name: "Root Knife",
          Damage: "d6",
        },
      ],
      Gear: [
        "Rations (3 uses)",
        "Torch (3 uses)",
        "Iron Pot",
        "Healing Salve (restores 1d4 STR, 1 use)",
      ],
      PettyGear: [
        "Twine Bauble (petty, Ward once per day) - Ward: A silver circle 50ft across appears on the ground. Choose one species that cannot cross it.",
      ],
      Names: [
        "Gunther",
        "Moss",
        "Fern",
        "Lichen",
        "Root",
        "Willow",
        "Sage",
        "Yarrow",
        "Rowan",
        "Ash",
      ],
      HistoryLabel: "How has the Wood failed you?",
      Histories: [
        "An ill-tempered forest spirit cursed you for stealing, marking you as an enemy of their kind. Take a Bezoar Stone. Ingesting it cures any poison (1 use, unless retrieved).",
        "A close friend disappeared into the forest. Now you see their face in any tea you brew. Take a Soporific Concoction (3 uses).",
      ],
      SpecialLabel: "What keeps you safe while in the Wood?",
      Specials: [
        "Amadou - A vermilion fungus that catches fire quite easily (3 uses).",
        "Delphinium - Breathe water for up to one hour (1 use, but can be divided into fractional doses).",
        "Tacky Stalk - A woody reed that hardens into a permanent adhesive when chewed (2 uses).",
        "Wisp Lantern - Caged in wrought iron, provides a dim light so long as the wisp is able to feed on nearby pain and fear.",
        "Seed Bomb - A canvas sack filled with seeds that explode on impact. d6 damage (blast, 3 uses). ",
        "Briarvine - Entangles any creature up to horse size (STR to break free, reusable).",
      ],
    },
    // {
    //   Name: "Half Witch",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Hexenbane",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Jongleur",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Kettlewright",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Marchguard",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Mountebank",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Outrider",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Prowler",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Rill Runner",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
    // {
    //   Name: "Scrivener",
    //   Description:
    //     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
    //   GoldDice: [3, 6],
    //   Weapons: [
    //     {
    //       Name: "Stake",
    //       Damage: "d6",
    //     },
    //   ],
    //   Gear: [
    //     "Rations (3 uses)",
    //     "Lantern",
    //     "Oil Can (6 uses)",
    //     "Chains (10ft)",
    //   ],
    //   PettyGear: [],
    //   Names: [
    //     "Rook",
    //     "Ebon",
    //     "Moro",
    //     "Yew",
    //     "Pall",
    //     "Leth",
    //     "Lenore",
    //     "Barnaby",
    //     "Vesper",
    //     "Leder",
    //   ],
    //   Histories: [
    //     "A Crow-Shaped Amulet. You can ask a question of the dead but must add a Fatigue each time.",
    //     "A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance but are still subject to pain and death. Trapped between worlds, the dead see you as one of their own.",
    //     "A Blood Pail (bulky) from a local death-cult. Empty it to raise a servant built from whatever is buried below, with 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, and shard fists (d8+d8). Only one servant can be raised at a time. If destroyed, you permanently lose 1d4 STR. Recharge: Fill with the blood of a dying warrior.",
    //     "A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, only +2 slots if pulling wagon, slow).",
    //     "The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate. Detect Magic: You can see or hear nearby magical auras. Becomes warm to the touch when magic is used nearby.",
    //     "A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
    //   ],
    // },
  ],
  Physiques = [
    "Athletic",
    "Brawny",
    "Flabby",
    "Lanky",
    "Rugged",
    "Scrawny",
    "Short",
    "Statuesque",
    "Stout",
    "Towering",
  ],
  Skins = [
    "Birthmarked",
    "Marked",
    "Oily",
    "Rosy",
    "Scarred",
    "Soft",
    "Tanned",
    "Tattooed",
    "Weathered",
    "Webbed",
  ],
  Hairs = [
    "Bald",
    "Braided",
    "Curly",
    "Filthy",
    "Frizzy",
    "Long",
    "Luxurious",
    "Oily",
    "Wavy",
    "Wispy",
  ],
  Faces = [
    "Bony",
    "Broken",
    "Chiseled",
    "Elognated",
    "Pale",
    "Perfect",
    "Rakish",
    "Sharp",
    "Square",
    "Sunken",
  ],
  Speech = [
    "Blunt",
    "Booming",
    "Cryptic",
    "Droning",
    "Formal",
    "Gravelly",
    "Precise",
    "Squeaky",
    "Stuttering",
    "Whispery",
  ],
  Clothing = [
    "Antique",
    "Bloody",
    "Elegant",
    "Filthy",
    "Foreign",
    "Frayed",
    "Frumpy",
    "Livery",
    "Rancid",
    "Soiled",
  ],
  Virtues = [
    "Ambitious",
    "Cautious",
    "Courageous",
    "Disciplined",
    "Gregarious",
    "Honorable",
    "Humble",
    "Merciful",
    "Serene",
    "Tolerant",
  ],
  Vices = [
    "Aggressive",
    "Bitter",
    "Craven",
    "Deceitful",
    "Greedy",
    "Lazy",
    "Nervous",
    "Rude",
    "Vain",
    "Vengeful",
  ];
